
services:
  nginx:
    build: .
    ports:
      - "23333:80"
    environment:
      - WASABI_ACCESS_KEY=${WASABI_ACCESS_KEY}
      - WASABI_SECRET_KEY=${WASABI_SECRET_KEY}
      - WASABI_BUCKET=${WASABI_BUCKET}
      - WASABI_REGION=${WASABI_REGION}
      - WASABI_PREFIX=${WASABI_PREFIX}
      - WASABI_HOST=${WASABI_HOST}
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/include:/etc/nginx/include
      - ./tmp/log:/var/log/nginx
      - ./tmp/cache:/opt/nginx

