# upstream service {
#     least_conn;
#     server 64.225.104.117;
# }

# default swarm upstream
upstream brazil {
    server 100.113.233.128;
    # least_conn;
    # hash $real_client_ip consistent;
    # server 100.94.219.12 max_fails=3 fail_timeout=10s;
    # server 100.121.43.40 max_fails=3 fail_timeout=10s;
    # server 100.99.236.109 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25 max_fails=3 fail_timeout=10s;
}

upstream brazil-adminka {
    server 100.113.233.128:55621;
}

# resizer imager
upstream brazil-resizer {
    least_conn;
    server 100.94.219.12:56777 max_fails=3 fail_timeout=10s;
    server 100.121.43.40:56777 max_fails=3 fail_timeout=10s;
    server 100.99.236.109:56777 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:56777 max_fails=3 fail_timeout=10s;
    # server 146.120.56.252:56777 max_fails=3 fail_timeout=10s;
    # server 31.128.246.28:56777 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:56777 max_fails=3 fail_timeout=10s;
}

# resizer imaginary
upstream brazil-resizer-imaginary {
    least_conn;
    server 100.94.219.12:56778 max_fails=3 fail_timeout=10s;
    server 100.121.43.40:56778 max_fails=3 fail_timeout=10s;
    server 100.99.236.109:56778 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:56778 max_fails=3 fail_timeout=10s;
    # server 146.120.56.252:56778 max_fails=3 fail_timeout=10s;
    # server 31.128.246.28:56778 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:56778 max_fails=3 fail_timeout=10s;
}

# only topflix.day and seriesflixbr.me
upstream brazil-flixproxy-topflix {
    # least_conn;
    hash $real_client_ip consistent;
    server 100.94.219.12:54621 max_fails=3 fail_timeout=10s; 
    server 100.121.43.40:54621 max_fails=3 fail_timeout=10s; 
    server 100.99.236.109:54621 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:54621 max_fails=3 fail_timeout=10s; 
    # server 146.120.56.252:54621 max_fails=3 fail_timeout=10s; 
    # server 31.128.246.28:54621 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:54621 max_fails=3 fail_timeout=10s;
}

#dle sites
upstream brazil-flixproxy {
    # least_conn;
    hash $real_client_ip consistent;
    server 100.94.219.12:54621 max_fails=3 fail_timeout=10s; 
    server 100.121.43.40:54621 max_fails=3 fail_timeout=10s; 
    server 100.99.236.109:54621 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:54621 max_fails=3 fail_timeout=10s; 
    # server 146.120.56.252:54621 max_fails=3 fail_timeout=10s; 
    # server 31.128.246.28:54621 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:54621 max_fails=3 fail_timeout=10s;
}

upstream brazil-vbalancer {
    # least_conn;
    hash $real_client_ip consistent;
    server 100.94.219.12:28091 max_fails=3 fail_timeout=10s; 
    server 100.121.43.40:28091 max_fails=3 fail_timeout=10s; 
    server 100.99.236.109:28091 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:28091 max_fails=3 fail_timeout=10s; 
    # server 146.120.56.252:28091 max_fails=3 fail_timeout=10s; 
    # server 31.128.246.28:28091 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:28091 max_fails=3 fail_timeout=10s;
}