# upstream service {
#     least_conn;
#     server 64.225.104.117;
# }

# default swarm upstream
upstream brazil {
    server 100.126.19.113;
    # least_conn;
    # hash $real_client_ip consistent;
    # server 100.123.186.39 max_fails=3 fail_timeout=10s;
    # server 100.85.105.44 max_fails=3 fail_timeout=10s;
    # server 100.125.75.128 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25 max_fails=3 fail_timeout=10s;
}

upstream brazil-adminka {
    server 100.126.19.113:55621;
}

# resizer imager
upstream brazil-resizer {
    least_conn;
    server 100.123.186.39:56777 max_fails=3 fail_timeout=10s;
    server 100.85.105.44:56777 max_fails=3 fail_timeout=10s;
    server 100.125.75.128:56777 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:56777 max_fails=3 fail_timeout=10s;
    # server 146.120.56.252:56777 max_fails=3 fail_timeout=10s;
    # server 31.128.246.28:56777 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:56777 max_fails=3 fail_timeout=10s;
}

# resizer imaginary
upstream brazil-resizer-imaginary {
    least_conn;
    server 100.123.186.39:56778 max_fails=3 fail_timeout=10s;
    server 100.85.105.44:56778 max_fails=3 fail_timeout=10s;
    server 100.125.75.128:56778 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:56778 max_fails=3 fail_timeout=10s;
    # server 146.120.56.252:56778 max_fails=3 fail_timeout=10s;
    # server 31.128.246.28:56778 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:56778 max_fails=3 fail_timeout=10s;
}

# only topflix.day and seriesflixbr.me
upstream brazil-flixproxy-topflix {
    # least_conn;
    hash $real_client_ip consistent;
    server 100.123.186.39:54621 max_fails=3 fail_timeout=10s; 
    server 100.85.105.44:54621 max_fails=3 fail_timeout=10s; 
    server 100.125.75.128:54621 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:54621 max_fails=3 fail_timeout=10s; 
    # server 146.120.56.252:54621 max_fails=3 fail_timeout=10s; 
    # server 31.128.246.28:54621 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:54621 max_fails=3 fail_timeout=10s;
}

#dle sites
upstream brazil-flixproxy {
    # least_conn;
    hash $real_client_ip consistent;
    server 100.123.186.39:54621 max_fails=3 fail_timeout=10s; 
    server 100.85.105.44:54621 max_fails=3 fail_timeout=10s; 
    server 100.125.75.128:54621 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:54621 max_fails=3 fail_timeout=10s; 
    # server 146.120.56.252:54621 max_fails=3 fail_timeout=10s; 
    # server 31.128.246.28:54621 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:54621 max_fails=3 fail_timeout=10s;
}

upstream brazil-vbalancer {
    # least_conn;
    hash $real_client_ip consistent;
    server 100.123.186.39:28091 max_fails=3 fail_timeout=10s; 
    server 100.85.105.44:28091 max_fails=3 fail_timeout=10s; 
    server 100.125.75.128:28091 max_fails=3 fail_timeout=10s;
    # server 146.120.56.253:28091 max_fails=3 fail_timeout=10s; 
    # server 146.120.56.252:28091 max_fails=3 fail_timeout=10s; 
    # server 31.128.246.28:28091 max_fails=3 fail_timeout=10s;
    # server 45.10.90.25:28091 max_fails=3 fail_timeout=10s;
}