server {
  listen 80;
  server_name cdn32.ntcdn.pro nginx.brazil-edge.orb.local;

  set_by_lua_block $s3_bucket { return os.getenv("WASABI_BUCKET") or "" }
  set_by_lua_block $s3_region { return os.getenv("WASABI_REGION") or "" }
  set_by_lua_block $s3_prefix { return os.getenv("WASABI_PREFIX") or "" }
  set_by_lua_block $s3_host { return os.getenv("WASABI_HOST") or "" }

  location ~ ^/testme/(?<rest>.*)$ {
    set $s3_key $rest;
    if ($s3_prefix != "") {
      set $s3_key "$s3_prefix/$rest";
    }
    set $s3_uri "/$s3_bucket/$s3_key";

    # подписываем запрос
    access_by_lua_block {
        local sigv4 = require "sigv4_wasabi"
        sigv4.sign_request()
    }

    if ($request_method = OPTIONS) {
        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
        add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range" always;
        add_header Access-Control-Max-Age 86400 always;
        return 204;
    }
    proxy_hide_header Access-Control-Allow-Origin;
    proxy_hide_header Access-Control-Allow-Methods;
    proxy_hide_header Access-Control-Allow-Headers;
    proxy_hide_header Access-Control-Expose-Headers;
    proxy_hide_header Access-Control-Max-Age;
    proxy_hide_header Content-Type;
    add_header Cache-Control "public, max-age=31536000, immutable" always;
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
    add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;

    # сбросить alt-svc (запретить/очистить h3 объявления)
    add_header Alt-Svc 'clear' always;

    limit_conn static_conn 10;
    limit_req  zone=static_req burst=20 nodelay;
    limit_conn_status 429;
    limit_req_status 429;

    proxy_intercept_errors on;
    proxy_ssl_server_name on;
    proxy_ssl_name $s3_host;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $s3_host;
    proxy_set_header Range $http_range;
    proxy_pass_header Content-Type;
    proxy_hide_header x-wasabi-cm-reference-id;
    proxy_hide_header Server;
    proxy_hide_header x-amz-id-2;
    proxy_hide_header x-amz-meta-mtime;
    proxy_hide_header x-amz-request-id;
    add_header X-Proxy-Cache-Status $upstream_cache_status always;

    proxy_cache backend_cache;
    proxy_no_cache $flag_cache_empty $http_range;
    proxy_cache_bypass $flag_cache_empty $http_range;
    proxy_cache_revalidate off;
    proxy_cache_valid 200 999h;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    proxy_cache_background_update on;
    proxy_cache_lock on;
    proxy_cache_lock_timeout 10s;
    proxy_cache_lock_age 10s;
    proxy_cache_key "$uri";
    proxy_pass https://$s3_host$s3_uri;
  }

  location /healthz { return 200 "ok\n"; }

  location = /favicon.ico { 
      access_log off;
      log_not_found off;
      add_header Content-Type text/plain; 
      return 404; 
  }
}